version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var/pgdata:/var/lib/postgresql/data
    networks:
      - application
    container_name: postgres_db
  python:
    container_name: app_container
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    networks:
      - application
    depends_on:
      - postgres
networks:
  application:
    driver: bridge
volumes:
  postgres:
  python:
