version: "3.9"

service:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var/pgdata:/var/lib/postgresql/data
    network:
      - application
    container_name: postgres_db
  app:
    container_name: app_container
    restart: always
    build: .
    ports:
      - "4000:4000"
    network:
      - application
    depends_on:
      - db
networks:
  application:
    driver: bridge
volumes:
  db_data:
