version: "3"

services:
  mysql:
    container_name: mysql_container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    volumes:
      - ./var/mysql:/var/lib/mysql
      
  python:
    container_name: app_container
    build: .
    restart: always
    environment:
      DB: mysql
      DB_DRIVER: pymysql
      DB_HOST: mysql
      DB_NAME: docker
      DB_USER: docker
      DB_PASSWORD: docker
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  mysql:
