version: "3"

services:
  mysql:
    container_name: mysql_container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    volumes:
      - ./var/mysql:/var/lib/mysql
    networks:
      - application
  python:
    container_name: app_container
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    networks:
      - application
    depends_on:
      - mysql
networks:
  application:
    driver: bridge
volumes:
  mysql:
  python:
